services:
  - type: web
    name: a100-project
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: COINGLASS_API_KEY
        sync: false
      - key: DEFAULT_SYMBOLS
        value: BTC,ETH,SOL,ARKM,SYN,SENT,ALT,VANRY,CELO,COTI,NFP,TIA,INJ,WLD,ZEC,KAITO,APE
      - key: SCORE_ALERT
        value: "85"
      - key: TOP_SCAN_LIMIT
        value: "50"
