services:
  - type: web
    name: a100-project
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: COINGLASS_API_KEY
        sync: false
      - key: DEFAULT_SYMBOLS
        value: ARKM,SYN,SENT,VANRY,ALT
      - key: SCORE_ALERT
        value: "80"
